change test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,25 +1,36 @@
-name: my first pipeline
+name: My first pipeline
 on: push
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v4 
       - name: Build image
-        run: docker build -t ${{secrets.DOCKER_USERNAME}}/ciportfolio .
+        run: |
+         docker build -t ${{secrets.DOCKER_USERNAME}}/ciportofolio:${{github.run_number}} .
+         docker build -t ${{secrets.DOCKER_USERNAME}}/ciportofolio .
       - name: Docker login
         uses: docker/login-action@v4
         with:
-          username: ${{secrets.DOCKER_USERNAME}}
-          password: ${{secrets.DOCKER_PASSWORD}}
-          
-          
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Push image to registry
-        run: docker push ${{secrets.DOCKER_USERNAME}}/ciportfolio
-
-deploy:
+        run: |
+         docker push ${{secrets.DOCKER_USERNAME}}/ciportofolio:${{github.run_number}}
+         docker push ${{secrets.DOCKER_USERNAME}}/ciportofolio
+      
+  deploy:
     needs: build
     runs-on: ubuntu-latest
     steps:
-      - name: ssh to Linux and run container
+      - name: SSh to Linux and run container
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.USERNAME }}
+          key: ${{ secrets.KEY }}
+          script: |
+              docker rm -f portfolio || echo "container not found,skipping removal"
+              docker run -d --name portfolio -p 8080:80 ${{secrets.DOCKER_USERNAME}}/ciportofolio
+
